import type {
  DashboardStat,
  DashboardBookingStatusStat,
  DashboardRecentBooking,
  DashboardPendingApproval,
  DashboardUpcomingArrival,
} from '../app/components/Dashboard';

export const mockStats: DashboardStat[] = [
  { label: 'Total Customers', value: '2,847', iconKey: 'users', change: '+12%', colorTone: 'blue' },
  { label: "Today's Bookings", value: '48', iconKey: 'calendar', change: '+8%', colorTone: 'green' },
  { label: 'Pending Reviews', value: '15', iconKey: 'clock', change: '-3%', colorTone: 'orange' },
  { label: 'Revenue (MTD)', value: 'HK$356K', iconKey: 'dollar', change: '+15%', colorTone: 'purple' },
];

export const mockBookingStatusStats: DashboardBookingStatusStat[] = [
  { label: 'Pending for Review', value: 8, colorTone: 'yellow' },
  { label: 'Pending for Approval', value: 7, colorTone: 'blue' },
  { label: 'Awaiting Payment', value: 12, colorTone: 'orange' },
  { label: 'Confirmed Today', value: 21, colorTone: 'green' },
];

export const mockRecentBookings: DashboardRecentBooking[] = [
  { id: 1045, bookingNo: 'A-202602-001045', guestName: 'John Smith', suite: 'VIP Suite A', time: '14:30', flightNo: 'CX889', status: 'Confirmed', paymentStatus: 'Paid', isAdHoc: false },
  { id: 1046, bookingNo: 'A-202602-001046', guestName: 'Mary Johnson', suite: 'Executive Suite', time: '15:00', flightNo: 'BA031', status: 'PendingForReview', paymentStatus: 'Pending', isAdHoc: true },
  { id: 1047, bookingNo: 'A-202602-001047', guestName: 'David Lee', suite: 'VIP Suite B', time: '16:30', flightNo: 'SQ001', status: 'Confirmed', paymentStatus: 'Paid', isAdHoc: false },
  { id: 1048, bookingNo: 'A-202602-001048', guestName: 'Sarah Chen', suite: 'Business Suite', time: '17:00', flightNo: 'NH859', status: 'PendingForApproval', paymentStatus: 'Pending', isAdHoc: false },
  { id: 1049, bookingNo: 'A-202602-001049', guestName: 'Robert Wang', suite: 'Premier Suite', time: '18:00', flightNo: 'QF029', status: 'Approved', paymentStatus: 'PaymentLinkSent', isAdHoc: false },
];

export const mockPendingBookings: DashboardPendingApproval[] = [
  {
    id: 1046,
    bookingNo: 'A-202602-001046',
    guestName: 'Mary Johnson',
    type: 'New',
    bookingTypeLabel: 'Ad-hoc Booking',
    suite: 'Executive Suite',
    submitted: '30 mins ago',
    priority: 'urgent',
    date: '2026-03-08',
    time: '15:00',
    flightNo: 'BA031',
    flightTime: '18:30',
    pax: 2,
    specialRequests: 'Vegetarian meal required',
    contactPhone: '+852 9123 4567',
    accountType: 'Individual',
  },
  {
    id: 1052,
    bookingNo: 'A-202602-001052',
    guestName: 'David Chen',
    type: 'Edit',
    bookingTypeLabel: 'VIP Suite A',
    suite: 'Premier Suite',
    submitted: '1 hour ago',
    priority: 'normal',
    date: '2026-03-10',
    time: '10:00',
    flightNo: 'CX889',
    flightTime: '13:45',
    pax: 1,
    specialRequests: 'Changed from VIP Suite A to Premier Suite',
    contactPhone: '+852 9234 5678',
    accountType: 'Corporate',
    originalSuite: 'VIP Suite A',
    originalDate: '2026-03-10',
    originalTime: '10:00',
    originalPax: 1,
    originalFlightNo: 'CX889',
    originalFlightTime: '13:45',
  },
  {
    id: 1038,
    bookingNo: 'A-202602-001038',
    guestName: 'Sarah Williams',
    type: 'Cancel',
    bookingTypeLabel: 'Business Suite',
    suite: 'Business Suite',
    submitted: '2 hours ago',
    priority: 'normal',
    date: '2026-03-12',
    time: '14:30',
    flightNo: 'SQ001',
    flightTime: '17:20',
    pax: 3,
    specialRequests: 'Cancellation reason: Travel plans changed',
    contactPhone: '+852 9345 6789',
    accountType: 'Individual',
  },
  {
    id: 1055,
    bookingNo: 'A-202602-001055',
    guestName: 'Michael Lee',
    type: 'New',
    bookingTypeLabel: 'Corporate Booking',
    suite: 'VIP Suite B',
    submitted: '3 hours ago',
    priority: 'normal',
    date: '2026-03-15',
    time: '09:30',
    flightNo: 'NH859',
    flightTime: '12:15',
    pax: 4,
    specialRequests: 'Meeting room setup required',
    contactPhone: '+852 9456 7890',
    accountType: 'Corporate',
  },
  {
    id: 1043,
    bookingNo: 'A-202602-001043',
    guestName: 'Emma Zhang',
    type: 'Edit',
    bookingTypeLabel: 'Premier Suite',
    suite: 'VIP Suite A',
    submitted: '5 hours ago',
    priority: 'urgent',
    date: '2026-03-09',
    time: '16:00',
    flightNo: 'QF029',
    flightTime: '19:45',
    pax: 2,
    specialRequests: 'Changed time from 14:00 to 16:00',
    contactPhone: '+852 9567 8901',
    accountType: 'Travel Agency',
    originalSuite: 'Premier Suite',
    originalDate: '2026-03-09',
    originalTime: '14:00',
    originalPax: 2,
    originalFlightNo: 'QF029',
    originalFlightTime: '19:45',
  },
];

export const mockUpcomingArrivals: DashboardUpcomingArrival[] = [
  { time: '14:00-15:00', count: 8, flightCount: 6 },
  { time: '15:00-16:00', count: 12, flightCount: 9 },
  { time: '16:00-17:00', count: 15, flightCount: 11 },
  { time: '17:00-18:00', count: 9, flightCount: 7 },
];

export const mockAvailableSuites = 8;
export const mockOccupiedSuites = 12;
