import type { OpportunityTrackingOpportunity } from '../app/components/OpportunityTracking';

export const mockOpportunities: OpportunityTrackingOpportunity[] = [
  {
    id: 1,
    opportunityRef: 'OPP-2025-0001',
    companyName: 'Cathay Pacific Airways',
    accountNumber: 'CORP-2024-0001',
    accountType: 'Corporate',
    contactName: 'Alice Lam',
    contactEmail: 'alice.lam@cathaypacific.com',
    stage: 'Renewal Due',
    estimatedValue: 168000,
    currency: 'HKD',
    expectedCloseDate: '2025-03-31',
    assignedTo: 'Kelly Chan',
    createdDate: '2024-12-01',
    lastActivityDate: '2025-02-18',
    description: 'Annual contract renewal. Client is happy but may seek Enterprise upgrade.',
    notes: 'Alice mentioned possible headcount growth. Explore Enterprise Bundle.',
    interactions: [
      { id: 1, date: '2025-02-18', type: 'Meeting', summary: 'Renewal discussion. Client satisfied. Interested in upgrade options.', followUpDate: '2025-03-01', conductedBy: 'Kelly Chan' },
      { id: 2, date: '2025-01-20', type: 'Call', summary: 'Check-in call. No issues. Confirmed renewal intent.', conductedBy: 'Kelly Chan' },
      { id: 3, date: '2024-12-15', type: 'Email', summary: 'Sent renewal proposal and pricing sheet.', conductedBy: 'Kelly Chan' },
    ],
  },
  {
    id: 2,
    opportunityRef: 'OPP-2025-0002',
    companyName: 'Goldman Sachs HK',
    accountNumber: 'PROSPECT-001',
    accountType: 'Corporate',
    contactName: 'Michael Yung',
    contactEmail: 'm.yung@gs.com',
    stage: 'Proposal Sent',
    estimatedValue: 280000,
    currency: 'HKD',
    expectedCloseDate: '2025-04-15',
    assignedTo: 'David Lau',
    createdDate: '2025-01-10',
    lastActivityDate: '2025-02-10',
    description: 'New enterprise prospect. CFO office has 30+ frequent flyers per month.',
    notes: 'Decision maker is CFO. Proposal sent for Enterprise Bundle.',
    interactions: [
      { id: 1, date: '2025-02-10', type: 'Meeting', summary: 'Presented Enterprise Bundle proposal. Price negotiation expected.', followUpDate: '2025-02-24', conductedBy: 'David Lau' },
      { id: 2, date: '2025-01-22', type: 'Site Visit', summary: 'Hosted Michael for lounge tour. Very positive feedback.', conductedBy: 'David Lau' },
      { id: 3, date: '2025-01-10', type: 'Call', summary: 'Initial discovery call. Identified 30+ travellers/month.', conductedBy: 'David Lau' },
    ],
  },
  {
    id: 3,
    opportunityRef: 'OPP-2025-0003',
    companyName: 'Fortune Travel Group',
    accountNumber: 'TA-2024-0003',
    accountType: 'Travel Agency',
    contactName: 'Gary Tsang',
    contactEmail: 'gary.tsang@fortunetravel.com',
    stage: 'Negotiation',
    estimatedValue: 160000,
    currency: 'HKD',
    expectedCloseDate: '2025-03-15',
    assignedTo: 'Kelly Chan',
    createdDate: '2025-01-05',
    lastActivityDate: '2025-02-21',
    description: 'Upsell from Business to Enterprise Bundle. Balance nearly depleted.',
    notes: 'Gary is pushing for 5% discount on Enterprise. Approved by manager.',
    interactions: [
      { id: 1, date: '2025-02-21', type: 'Call', summary: 'Negotiating discount terms. Gary accepted 3%.', followUpDate: '2025-02-28', conductedBy: 'Kelly Chan' },
      { id: 2, date: '2025-02-05', type: 'Meeting', summary: 'Presented upsell options. Client interested in Enterprise.', conductedBy: 'Kelly Chan' },
    ],
  },
  {
    id: 4,
    opportunityRef: 'OPP-2025-0004',
    companyName: 'Pacific World Travel',
    accountNumber: 'TA-2024-0002',
    accountType: 'Travel Agency',
    contactName: 'Fiona Cheung',
    contactEmail: 'fiona@pacificworld.hk',
    stage: 'Prospecting',
    estimatedValue: 32000,
    currency: 'HKD',
    expectedCloseDate: '2025-05-01',
    assignedTo: 'David Lau',
    createdDate: '2025-02-22',
    lastActivityDate: '2025-02-22',
    description: 'Newly onboarded. Standard Bundle trial. Assess utilisation for upsell in Q3.',
    notes: 'Monitor usage in first 3 months.',
    interactions: [
      { id: 1, date: '2025-02-22', type: 'Email', summary: 'Welcome email sent with onboarding guide.', conductedBy: 'David Lau' },
    ],
  },
  {
    id: 5,
    opportunityRef: 'OPP-2024-0005',
    companyName: 'HSBC Hong Kong',
    accountNumber: 'CORP-2024-0002',
    accountType: 'Corporate',
    contactName: 'Brian Wong',
    contactEmail: 'brian.wong@hsbc.com',
    stage: 'Closed Won',
    estimatedValue: 3800,
    currency: 'HKD',
    expectedCloseDate: '2024-03-20',
    assignedTo: 'Kelly Chan',
    createdDate: '2024-02-15',
    lastActivityDate: '2024-03-20',
    description: 'Basic Bundle sold. Entry-level package.',
    notes: 'Watch for utilisation — potential to upgrade to Standard.',
    interactions: [
      { id: 1, date: '2024-03-20', type: 'Call', summary: 'Contract signed. Basic Bundle activated.', conductedBy: 'Kelly Chan' },
      { id: 2, date: '2024-03-01', type: 'Meeting', summary: 'Signed off on Basic Bundle terms.', conductedBy: 'Kelly Chan' },
    ],
  },
  {
    id: 6,
    opportunityRef: 'OPP-2024-0006',
    companyName: 'DHL Express HK',
    accountNumber: 'PROSPECT-002',
    accountType: 'Corporate',
    contactName: 'Tom Leung',
    contactEmail: 't.leung@dhl.com',
    stage: 'Closed Lost',
    estimatedValue: 56000,
    currency: 'HKD',
    expectedCloseDate: '2024-11-30',
    assignedTo: 'David Lau',
    createdDate: '2024-09-01',
    lastActivityDate: '2024-11-30',
    description: 'Lost to competitor — preferred in-terminal lounge contract.',
    notes: 'Re-approach Q3 2025 when their contract expires.',
    interactions: [
      { id: 1, date: '2024-11-30', type: 'Email', summary: 'Client confirmed they signed with competitor.', conductedBy: 'David Lau' },
      { id: 2, date: '2024-10-15', type: 'Meeting', summary: 'Final pitch. Strong competition from CX Lounge.', conductedBy: 'David Lau' },
    ],
  },
];
