import type { PromoCodeListBatch } from '../app/components/PromoCodeList';

export const mockPromoBatches: PromoCodeListBatch[] = [
  {
    id: 1,
    companyId: 1,
    companyName: 'Cathay Pacific Airways',
    companyShortCode: 'CPA',
    prefix: 'CPA',
    titleEn: 'Cathay Pacific Welcome Offer',
    titleTradChi: '國泰航空歡迎優惠',
    codeType: 'Discount',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    reusable: false,
    amount: 15,
    useLimit: 1,
    totalCodes: 200,
    usedCount: 45,
    availability: true,
    sampleCodes: ['CPA-A3B7C2', 'CPA-X9Y4Z1', 'CPA-M5N8P3'],
  },
  {
    id: 7,
    companyId: 1,
    companyName: 'Cathay Pacific Airways',
    companyShortCode: 'CPA',
    prefix: 'CPAVIP',
    titleEn: 'Cathay Pacific VIP Elite',
    titleTradChi: '國泰航空至尊貴賓',
    codeType: 'Free bookings',
    startDate: '2026-03-01',
    endDate: '2026-09-30',
    reusable: true,
    amount: 3,
    useLimit: 2,
    totalCodes: 80,
    usedCount: 12,
    availability: true,
    sampleCodes: ['CPAVIP-Q1R2S3', 'CPAVIP-T4U5V6'],
  },
  {
    id: 2,
    companyId: 2,
    companyName: 'HSBC Hong Kong',
    companyShortCode: 'HSBC',
    prefix: 'HSBC',
    titleEn: 'HSBC Staff Complimentary Lounge',
    titleTradChi: '滙豐員工免費貴賓室',
    codeType: 'Free bookings',
    startDate: '2026-02-01',
    endDate: '2026-06-30',
    reusable: false,
    amount: 2,
    useLimit: 1,
    totalCodes: 500,
    usedCount: 128,
    availability: true,
    sampleCodes: ['HSBC-T2R4W8', 'HSBC-K6L9M2', 'HSBC-P3Q7N5'],
  },
  {
    id: 3,
    companyId: 5,
    companyName: 'PwC Hong Kong',
    companyShortCode: 'PWC',
    prefix: 'PWC',
    titleEn: 'PwC Summer Special Discount',
    titleTradChi: 'PwC 夏季特別折扣',
    codeType: 'Discount',
    startDate: '2025-06-01',
    endDate: '2025-08-31',
    reusable: true,
    amount: 20,
    useLimit: 3,
    totalCodes: 100,
    usedCount: 92,
    availability: false,
    sampleCodes: ['PWC-D4F6H8', 'PWC-J2K5L7', 'PWC-N9P3Q6'],
  },
  {
    id: 4,
    companyId: 9,
    companyName: 'KPMG',
    companyShortCode: 'KPMG',
    prefix: 'KPMG',
    titleEn: 'KPMG New Year Offer',
    titleTradChi: 'KPMG 新年優惠',
    codeType: 'Discount',
    startDate: '2026-01-01',
    endDate: '2026-01-31',
    reusable: false,
    amount: 25,
    useLimit: 1,
    totalCodes: 300,
    usedCount: 198,
    availability: true,
    sampleCodes: ['KPMG-B5C8D2', 'KPMG-E4F7G1', 'KPMG-H3J6K9'],
  },
  {
    id: 8,
    companyId: 9,
    companyName: 'KPMG',
    companyShortCode: 'KPMG',
    prefix: 'KPMGQ2',
    titleEn: 'KPMG Q2 Loyalty Reward',
    titleTradChi: 'KPMG 第二季忠誠獎勵',
    codeType: 'Free bookings',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    reusable: false,
    amount: 1,
    useLimit: 1,
    totalCodes: 150,
    usedCount: 0,
    availability: true,
    sampleCodes: ['KPMGQ2-A1B2C3', 'KPMGQ2-D4E5F6'],
  },
  {
    id: 5,
    companyId: 14,
    companyName: 'Morgan Stanley',
    companyShortCode: 'MS',
    prefix: 'MS',
    titleEn: 'Morgan Stanley VIP Access',
    titleTradChi: '摩根士丹利貴賓通行',
    codeType: 'Free bookings',
    startDate: '2026-01-15',
    endDate: '2026-12-15',
    reusable: true,
    amount: 1,
    useLimit: 5,
    totalCodes: 150,
    usedCount: 56,
    availability: true,
    sampleCodes: ['MS-A7B2C4', 'MS-D9E3F6', 'MS-G5H8J1'],
  },
  {
    id: 6,
    companyId: 8,
    companyName: 'Deloitte',
    companyShortCode: 'DLT',
    prefix: 'DLT',
    titleEn: 'Deloitte Holiday Perk',
    titleTradChi: 'Deloitte 節日福利',
    codeType: 'Discount',
    startDate: '2023-12-01',
    endDate: '2023-12-31',
    reusable: false,
    amount: 15,
    useLimit: 1,
    totalCodes: 250,
    usedCount: 250,
    availability: false,
    sampleCodes: ['DLT-R2S5T8', 'DLT-U4V7W1', 'DLT-X3Y6Z9'],
  },
];
